 -- understanding the database
 select*from dim_date;
-- total 92 dates are present in our database

select distinct mon_yr from dim_date;
-- there are three different months in the database

select distinct week_no from dim_date;
-- 14 differnt weeks 

select distinct day_type from dim_date;
-- there are two different types of days


select *from dim_hotels;
-- there are 25 different hotels are under atliq

select distinct category from dim_hotels;
-- only two categories of hotels are present in atliq

select distinct city from dim_hotels;
-- all hotels are situated only in four different cities
 
select *from dim_rooms;
--there are four different classes of rooms

select*from fact_aggregated_bookings;

select COUNT(*) from fact_aggregated_bookings;
-- 9200 records

select*from fact_bookings;
-- total 134590 bookings

select COUNT(*)from fact_bookings;
-- 134590 records arepresent in fact_bookings

select COUNT(*) from fact_bookings
where ratings_given is null
-- 77907 are nulls ( the reason behind this much nulls because  of cancelled and no show customers )
--remaining columns don't have nulls

select distinct booking_platform from fact_bookings;
--there are 7 different types of booking_platforms are available for booking 

-- trimming of booking_date,check_in_date and checkout_date 

select SUBSTRING(cast(booking_date as nvarchar(50)),1,11) from fact_bookings

update fact_bookings
set booking_date=SUBSTRING(cast(booking_date as nvarchar(50)),1,11)

update fact_bookings
set booking_date=SUBSTRING(cast(check_in_date as nvarchar(50)),1,11)

update fact_bookings
set booking_date=SUBSTRING(cast(checkout_date as nvarchar(50)),1,11)


 select round(AVG(cast(ratings_given as decimal)),2)from fact_bookings
-- average rating of atliq grands is 3.62

create table #avg_rating_of_hotels
(hotel_id int not null,
rating_of_each_hotel decimal(18,2))

insert into #avg_rating_of_hotels (hotel_id,rating_of_each_hotel)

 select property_id,
round(SUM( cast(ratings_given as decimal))/ COUNT(ratings_given),2) as rating_of_each_hotel from fact_bookings
group by property_id
order by 2 desc;
-- avreage ratings of each hotel

select *from #avg_rating_of_hotels

select 
case when ratings_given IS NULL then rating_of_each_hotel else ratings_given end as new_ratings_given
from fact_bookings 
left join #avg_rating_of_hotels on 
#avg_rating_of_hotels.hotel_id=fact_bookings.property_id;



select SUM(revenue_realized) from fact_bookings;
-- total revenue realized is 1708771229


select booking_platform,COUNT(booking_id)as no_of_bookings from fact_bookings
group by booking_platform
order by 2 desc;
-- no_of_bookings on each different platform

select booking_status, COUNT(booking_id)as no_of_bookings,cast(COUNT(booking_id)/134590 as decimal)from fact_bookings
group by booking_status
order by 2 desc

select COUNT( case when booking_status='Checked Out'then booking_id end)as no_of_checkout_bookings,
       COUNT( case when booking_status='Cancelled' then booking_id end)  as no_of_cancelled_bookings,
       COUNT( case when booking_status='No Show'then booking_id end)  as no_of_noshow_bookings
       from fact_bookings;

--94411/134590=0.701 i.e  70.1% are successful bookings
--33420/134590=0.248 i.e almost 25% of total bookings are cancelled
--6759/134590=0.05 i.e 5% are noshow bookings

select room_class, count(booking_id)
from fact_bookings
left join dim_rooms
on dim_rooms.room_id=fact_bookings.room_category
group by room_class
order by 2 desc;
-- 49505/134590=0.367i.e 36.7% bookings are elite class
-- 38446/134590=0.285 i.e 28.5% are standard class
--30566/134590=0.227 i.e 22.7% are premium class 
-- 16073/134590=0.119 i.e 12% are presidential class

select property_id,count(booking_id)from fact_bookings
group by property_id
order by 2 desc;
-- no of bookings per hotel

select city, COUNT(booking_id)
from dim_hotels
left join fact_bookings on 
fact_bookings.property_id=dim_hotels.property_id
group by city;

select SUM(cast(capacity as int))  from fact_aggregated_bookings
-- total capacity of all hotels is 232576


select sum(cast(successful_bookings as decimal))/sum(cast(capacity as decimal)) from fact_aggregated_bookings

-- overall occupancy is 57.8%

select COUNT(booking_id) from fact_bookings where booking_status='cancelled'

--out of all bookings 33420 are cancelled

select COUNT(case when booking_status='cancelled' then booking_id end)/COUNT(booking_id)as cancellation_rate from fact_bookings

-- almost 25% of bookings got cancelled
select SUM(revenue_realized) from fact_bookings;
-- actual total revenue generated by atliq

select  sum(cast(successful_bookings as decimal(18,2)))/SUM(cast(capacity as decimal(18,2))) from fact_aggregated_bookings;
-- overall occupancy rate is 58% 

select round(AVG(cast(ratings_given as decimal(18,2))),2) from fact_bookings
-- overall average rating is 3.62

select city,sum(revenue_realized)as revenue_by_city
from fact_bookings
left join dim_hotels
on fact_bookings.property_id= dim_hotels.property_id
group by city
--city wise revenue

select city, sum(cast(successful_bookings as decimal(18,2)))/SUM(cast(capacity as decimal(18,2)))as occupancy_per_city
from fact_aggregated_bookings
left join dim_hotels on 
dim_hotels.property_id=fact_aggregated_bookings.property_id
group by city
order by 2 desc;
-- city wise occupancy

select booking_platform,count(booking_id) from fact_bookings
group by booking_platform
-- platform wise bookings

select city ,round(AVG(cast(ratings_given as decimal(18,2))),2) 
from dim_hotels
left join fact_bookings on
fact_bookings.property_id= dim_hotels.property_id
group by city
-- city wise average rating


select property_name,SUM(revenue_realized)
from dim_hotels 
left join fact_bookings
on fact_bookings.property_id=dim_hotels.property_id
group by property_name
order by 2 desc;
-- property name wise revenue

select room_class,SUM(revenue_realized) 
from dim_rooms 
left join fact_bookings on
fact_bookings.room_category=dim_rooms.room_id
group by room_class
order by 2 desc
--room class wise revenue

select category,COUNT(booking_id)
from  dim_hotels
left join fact_bookings on
dim_hotels.property_id=fact_bookings.property_id
where booking_status='Checked Out'
group by category
-- category wise successful bookings

select day_type,sum(cast(successful_bookings as decimal(18,2)))/SUM(cast(capacity as decimal(18,2)))
from dim_date
left join fact_aggregated_bookings on
fact_aggregated_bookings.check_in_date=dim_date.date
group by day_type
-- day type wise occupancy

select week_no,SUM(revenue_realized),round(AVG(cast(ratings_given as decimal(18,2))),2) 
from dim_date
left join fact_bookings on 
dim_date.date=fact_bookings.booking_date
group by  week_no
-- week wise revenue and average rating

select avg(cast(revenue_realized as decimal(18,2)))/COUNT(successful_bookings)
from fact_aggregated_bookings
right join fact_bookings on 
fact_aggregated_bookings.property_id=fact_bookings.property_id
--where booking_status='Checked Out'

select SUM(cast(revenue_realized as decimal(18,2)))/COUNT(booking_id) from fact_bookings
-- average daily rate

select SUM(cast(revenue_realized as decimal(18,2)))/COUNT(booking_id)*sum(cast(successful_bookings as decimal(18,2)))/SUM(cast(capacity as decimal(18,2)))
from fact_aggregated_bookings
left join fact_bookings
on fact_aggregated_bookings.property_id=fact_bookings.property_id
--  RevPAR(revenue per available room)

select city, SUM(cast(revenue_realized as decimal(18,2)))/COUNT(booking_id) from dim_hotels
left join fact_bookings on 
dim_hotels.property_id=fact_bookings.property_id
group by city
-- average daily rate per city

select room_class, SUM(cast(revenue_realized as decimal(18,2)))/COUNT(booking_id) from dim_rooms
left join fact_bookings on 
dim_rooms.room_id=fact_bookings.room_category
group by room_class
-- average daily rate per room class

select city,SUM(cast(revenue_realized as decimal(18,2)))/COUNT(booking_id)*sum(cast(successful_bookings as decimal(18,2)))/SUM(cast(capacity as decimal(18,2)))
from fact_aggregated_bookings
left join fact_bookings
on fact_aggregated_bookings.property_id=fact_bookings.property_id
right join  dim_hotels on
dim_hotels.property_id=fact_bookings.property_id
group by city
--  RevPAR(revenue per available room) by city


select room_class,SUM(cast(revenue_realized as decimal(18,2)))/COUNT(booking_id)*sum(cast(successful_bookings as decimal(18,2)))/SUM(cast(capacity as decimal(18,2)))
from fact_aggregated_bookings
left join fact_bookings
on fact_aggregated_bookings.property_id=fact_bookings.property_id
right join  dim_rooms on
dim_rooms.room_id=fact_bookings.room_category
group by room_class
--  RevPAR(revenue per available room) by room class

select week_no,SUM(cast(revenue_realized as decimal(18,2)))/COUNT(booking_id),
SUM(cast(revenue_realized as decimal(18,2)))/COUNT(booking_id)*sum(cast(successful_bookings as decimal(18,2)))/SUM(cast(capacity as decimal(18,2)))
from fact_aggregated_bookings
left join fact_bookings
on fact_aggregated_bookings.property_id=fact_bookings.property_id
right join  dim_date on
dim_date.date=fact_bookings.booking_date
group by week_no
--  RevPAR(revenue per available room) and avg daily rate by week no 